frase = str(input('Digite uma frase: ')).upper()
qtde_a = (frase.count('A'))
print('A letra A aparece', qtde_a, 'na frase')
posicao_a = (frase.find('A'))
print('A primeira letra A apareceu na posição', posicao_a)
x = (len(frase))
print('quantidade de caracteres',x)
fim_a = frase.rfind('A')
print('A última letra A apareceu na posição', fim_a)
